/*
 Navicat Premium Data Transfer

 Source Server         : zen-wms
 Source Server Type    : PostgreSQL
 Source Server Version : 150008 (150008)
 Source Host           : 217.21.78.155:57777
 Source Catalog        : postgres
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 150008 (150008)
 File Encoding         : 65001

 Date: 14/01/2026 15:41:16
*/


-- ----------------------------
-- Type structure for account_type
-- ----------------------------
DROP TYPE IF EXISTS "public"."account_type";
CREATE TYPE "public"."account_type" AS ENUM (
  'CASH',
  'BANK'
);
ALTER TYPE "public"."account_type" OWNER TO "supabase_admin";

-- ----------------------------
-- Type structure for po_status
-- ----------------------------
DROP TYPE IF EXISTS "public"."po_status";
CREATE TYPE "public"."po_status" AS ENUM (
  'DRAFT',
  'ISSUED',
  'PARTIAL',
  'COMPLETED',
  'CANCELLED',
  'PAID',
  'INVOICED'
);
ALTER TYPE "public"."po_status" OWNER TO "supabase_admin";

-- ----------------------------
-- Type structure for transaction_category_type
-- ----------------------------
DROP TYPE IF EXISTS "public"."transaction_category_type";
CREATE TYPE "public"."transaction_category_type" AS ENUM (
  'CAPITAL',
  'OTHER_INCOME',
  'REFUND',
  'EXPENSE_OPS',
  'EXPENSE_PURCHASE',
  'WITHDRAWAL',
  'PETTY_REFILL',
  'OTHERS'
);
ALTER TYPE "public"."transaction_category_type" OWNER TO "supabase_admin";

-- ----------------------------
-- Sequence structure for barang_price_history_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."barang_price_history_id_seq";
CREATE SEQUENCE "public"."barang_price_history_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for barang_prices_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."barang_prices_id_seq";
CREATE SEQUENCE "public"."barang_prices_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for barang_units_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."barang_units_id_seq";
CREATE SEQUENCE "public"."barang_units_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for group_outlet_group_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."group_outlet_group_id_seq";
CREATE SEQUENCE "public"."group_outlet_group_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for locations_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."locations_id_seq";
CREATE SEQUENCE "public"."locations_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for master_barang_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."master_barang_id_seq";
CREATE SEQUENCE "public"."master_barang_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for master_type_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."master_type_id_seq";
CREATE SEQUENCE "public"."master_type_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for trans_detail_autonum_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."trans_detail_autonum_seq";
CREATE SEQUENCE "public"."trans_detail_autonum_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for barang_price_history
-- ----------------------------
DROP TABLE IF EXISTS "public"."barang_price_history";
CREATE TABLE "public"."barang_price_history" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "barang_id" int8 NOT NULL,
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "old_price" numeric(15,2),
  "new_price" numeric(15,2),
  "price_type" text COLLATE "pg_catalog"."default",
  "changed_at" timestamptz(6) DEFAULT now(),
  "changed_by" uuid
)
;

-- ----------------------------
-- Table structure for barang_prices
-- ----------------------------
DROP TABLE IF EXISTS "public"."barang_prices";
CREATE TABLE "public"."barang_prices" (
  "barang_id" int8 NOT NULL,
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "buy_price" numeric(15,2) DEFAULT 0,
  "sell_price" numeric(15,2) DEFAULT 0,
  "updated_at" timestamptz(6) DEFAULT now(),
  "update_by" text COLLATE "pg_catalog"."default",
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
)
)
;

-- ----------------------------
-- Table structure for barang_units
-- ----------------------------
DROP TABLE IF EXISTS "public"."barang_units";
CREATE TABLE "public"."barang_units" (
  "barang_id" int8 NOT NULL,
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "base_uom" text COLLATE "pg_catalog"."default" DEFAULT 'PCS'::text,
  "purchase_uom" text COLLATE "pg_catalog"."default" DEFAULT 'PCS'::text,
  "conversion_rate" numeric(10,2) DEFAULT 1,
  "updated_at" timestamptz(6) DEFAULT now(),
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "update_by" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for finance_account_ledger
-- ----------------------------
DROP TABLE IF EXISTS "public"."finance_account_ledger";
CREATE TABLE "public"."finance_account_ledger" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "account_id" uuid NOT NULL,
  "transaction_type" text COLLATE "pg_catalog"."default" NOT NULL,
  "amount" numeric(15,2) NOT NULL,
  "description" text COLLATE "pg_catalog"."default",
  "ref_id" uuid,
  "balance_after" numeric(15,2),
  "created_at" timestamptz(6) DEFAULT now()
)
;

-- ----------------------------
-- Table structure for finance_ap_ledger
-- ----------------------------
DROP TABLE IF EXISTS "public"."finance_ap_ledger";
CREATE TABLE "public"."finance_ap_ledger" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "invoice_id" uuid NOT NULL,
  "kode_supplier" uuid,
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "original_amount" numeric(15,2) NOT NULL,
  "paid_amount" numeric(15,2) DEFAULT 0,
  "remaining_balance" numeric(15,2) GENERATED ALWAYS AS (
(original_amount - paid_amount)
) STORED,
  "due_date" date NOT NULL,
  "is_paid" bool DEFAULT false,
  "created_at" timestamptz(6) DEFAULT now(),
  "ref_outlet_id" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for finance_general_transactions
-- ----------------------------
DROP TABLE IF EXISTS "public"."finance_general_transactions";
CREATE TABLE "public"."finance_general_transactions" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "document_number" text COLLATE "pg_catalog"."default" NOT NULL,
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "financial_account_id" uuid NOT NULL,
  "transaction_type" text COLLATE "pg_catalog"."default",
  "amount" numeric(15,2) NOT NULL,
  "transaction_date" date DEFAULT CURRENT_DATE,
  "description" text COLLATE "pg_catalog"."default",
  "created_by" uuid,
  "created_at" timestamptz(6) DEFAULT now(),
  "category_id" uuid
)
;

-- ----------------------------
-- Table structure for finance_payment_allocations
-- ----------------------------
DROP TABLE IF EXISTS "public"."finance_payment_allocations";
CREATE TABLE "public"."finance_payment_allocations" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "payment_id" uuid NOT NULL,
  "invoice_id" uuid NOT NULL,
  "amount_allocated" numeric(15,2) NOT NULL,
  "discount_amount" numeric(15,2) DEFAULT 0
)
;

-- ----------------------------
-- Table structure for finance_payments_out
-- ----------------------------
DROP TABLE IF EXISTS "public"."finance_payments_out";
CREATE TABLE "public"."finance_payments_out" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "document_number" text COLLATE "pg_catalog"."default" NOT NULL,
  "kode_supplier" uuid,
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "financial_account_id" uuid NOT NULL,
  "total_amount" numeric(15,2) NOT NULL,
  "payment_date" date DEFAULT CURRENT_DATE,
  "notes" text COLLATE "pg_catalog"."default",
  "created_by" uuid,
  "created_at" timestamptz(6) DEFAULT now(),
  "ref_outlet_id" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for finance_transaction_categories
-- ----------------------------
DROP TABLE IF EXISTS "public"."finance_transaction_categories";
CREATE TABLE "public"."finance_transaction_categories" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "name" text COLLATE "pg_catalog"."default" NOT NULL,
  "type" text COLLATE "pg_catalog"."default" NOT NULL,
  "description" text COLLATE "pg_catalog"."default",
  "is_active" bool DEFAULT true,
  "created_at" timestamptz(6) DEFAULT now()
)
;

-- ----------------------------
-- Table structure for goods_receipt_items
-- ----------------------------
DROP TABLE IF EXISTS "public"."goods_receipt_items";
CREATE TABLE "public"."goods_receipt_items" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "receipt_id" uuid NOT NULL,
  "po_item_id" uuid NOT NULL,
  "barang_id" int8 NOT NULL,
  "qty_received" numeric(10,2) NOT NULL,
  "conversion_rate" numeric(10,2) NOT NULL,
  "qty_base_unit" numeric(15,2) GENERATED ALWAYS AS (
(qty_received * conversion_rate)
) STORED
)
;

-- ----------------------------
-- Table structure for goods_receipts
-- ----------------------------
DROP TABLE IF EXISTS "public"."goods_receipts";
CREATE TABLE "public"."goods_receipts" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "document_number" text COLLATE "pg_catalog"."default" NOT NULL,
  "po_id" uuid NOT NULL,
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "received_at" timestamptz(6) DEFAULT now(),
  "received_by" uuid,
  "supplier_delivery_note" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for group_outlet
-- ----------------------------
DROP TABLE IF EXISTS "public"."group_outlet";
CREATE TABLE "public"."group_outlet" (
  "group_id" int4 NOT NULL DEFAULT nextval('group_outlet_group_id_seq'::regclass),
  "created_at" timestamptz(6) DEFAULT now(),
  "group_name" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for inventory_balance
-- ----------------------------
DROP TABLE IF EXISTS "public"."inventory_balance";
CREATE TABLE "public"."inventory_balance" (
  "barang_id" int8 NOT NULL,
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "opening_balance" numeric(15,2) DEFAULT 0,
  "qty_on_hand" numeric(15,2) DEFAULT 0,
  "last_movement_at" timestamptz(6) DEFAULT now(),
  "date_ob" date
)
;

-- ----------------------------
-- Table structure for inventory_shrinkage_logs
-- ----------------------------
DROP TABLE IF EXISTS "public"."inventory_shrinkage_logs";
CREATE TABLE "public"."inventory_shrinkage_logs" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "document_number" text COLLATE "pg_catalog"."default" NOT NULL,
  "transaction_date" date DEFAULT CURRENT_DATE,
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "barang_id" int8 NOT NULL,
  "shrinkage_category_id" uuid NOT NULL,
  "qty_lost" numeric(10,2) NOT NULL,
  "notes" text COLLATE "pg_catalog"."default",
  "created_by" uuid,
  "created_at" timestamptz(6) DEFAULT now()
)
;

-- ----------------------------
-- Table structure for locations
-- ----------------------------
DROP TABLE IF EXISTS "public"."locations";
CREATE TABLE "public"."locations" (
  "id" int8 NOT NULL DEFAULT nextval('locations_id_seq'::regclass),
  "name" text COLLATE "pg_catalog"."default" NOT NULL,
  "location_code" text COLLATE "pg_catalog"."default" NOT NULL,
  "location_type" text COLLATE "pg_catalog"."default" NOT NULL,
  "is_active" bool DEFAULT true,
  "created_at" timestamptz(6) DEFAULT now(),
  "updated_at" timestamptz(6) DEFAULT now()
)
;

-- ----------------------------
-- Table structure for master_bank
-- ----------------------------
DROP TABLE IF EXISTS "public"."master_bank";
CREATE TABLE "public"."master_bank" (
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "kode_bank" uuid NOT NULL DEFAULT gen_random_uuid(),
  "bank_name" text COLLATE "pg_catalog"."default",
  "desc" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for master_barang
-- ----------------------------
DROP TABLE IF EXISTS "public"."master_barang";
CREATE TABLE "public"."master_barang" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "sku" text COLLATE "pg_catalog"."default" NOT NULL,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "id_type" int8,
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "name" text COLLATE "pg_catalog"."default",
  "deleted" bool DEFAULT false,
  "image1_url" text COLLATE "pg_catalog"."default",
  "iamge2_url" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for master_financial_accounts
-- ----------------------------
DROP TABLE IF EXISTS "public"."master_financial_accounts";
CREATE TABLE "public"."master_financial_accounts" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "account_name" text COLLATE "pg_catalog"."default" NOT NULL,
  "account_type" "public"."account_type" NOT NULL,
  "bank_name" text COLLATE "pg_catalog"."default",
  "account_number" text COLLATE "pg_catalog"."default",
  "balance" numeric(15,2) DEFAULT 0,
  "is_active" bool DEFAULT true,
  "created_at" timestamptz(6) DEFAULT now()
)
;

-- ----------------------------
-- Table structure for master_outlet
-- ----------------------------
DROP TABLE IF EXISTS "public"."master_outlet";
CREATE TABLE "public"."master_outlet" (
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "name_outlet" text COLLATE "pg_catalog"."default" NOT NULL,
  "alamat" text COLLATE "pg_catalog"."default",
  "no_telp" text COLLATE "pg_catalog"."default",
  "no_wa" text COLLATE "pg_catalog"."default",
  "location" json,
  "province" text COLLATE "pg_catalog"."default",
  "outlet_group_id" int4,
  "email" text COLLATE "pg_catalog"."default",
  "active" bool DEFAULT true,
  "city" text COLLATE "pg_catalog"."default",
  "can_sto" bool DEFAULT true
)
;

-- ----------------------------
-- Table structure for master_recipe_items
-- ----------------------------
DROP TABLE IF EXISTS "public"."master_recipe_items";
CREATE TABLE "public"."master_recipe_items" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "recipe_id" uuid NOT NULL,
  "material_barang_id" int8 NOT NULL,
  "qty_required" numeric(10,4) NOT NULL,
  "uom_usage" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for master_recipes
-- ----------------------------
DROP TABLE IF EXISTS "public"."master_recipes";
CREATE TABLE "public"."master_recipes" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "barang_id" int8 NOT NULL,
  "kode_outlet" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT '111'::text,
  "description" text COLLATE "pg_catalog"."default",
  "standard_qty_output" numeric(10,2) DEFAULT 1,
  "created_at" timestamptz(6) DEFAULT now()
)
;

-- ----------------------------
-- Table structure for master_shrinkage_categories