/**
 * Product Page - Master Data > Product
 *
 * CRUD operations for master_barang table with role-based access:
 * - Roles 1, 5, 6: Full CRUD access to own outlet's products
 * - Role 8: Read-only access to all products
 * - Roles 1, 8: Can see all outlets' products
 * - Roles 5, 6: Can only see their outlet's products
 */

import { useState, useEffect } from 'react'
import { useProductsPaginated, useCreateProduct, useUpdateProduct, useSoftDeleteProduct, useCanEditProducts, useCanSeeAllOutlets } from '@/hooks/useMasterBarang'
import { useAllTypes } from '@/hooks/useMasterType'
import { useAuthUser } from '@/hooks/useAuth'
import { ProtectedRoute } from '@/components/ProtectedRoute'
import { DashboardLayout } from '@/components/layout/Sidebar'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { toast } from 'sonner'
import { type MasterBarangWithType, type MasterType } from '@/types/database'
import { Plus, Pencil, Trash2, ChevronLeft, ChevronRight, Search } from 'lucide-react'

// ============================================
// FORM DIALOG COMPONENT
// ============================================

interface ProductFormDialogProps {
  isOpen: boolean
  onClose: () => void
  onSubmit: (data: Omit<MasterBarangWithType, 'id' | 'created_at' | 'kode_outlet' | 'master_type' | 'master_outlet'>) => Promise<void>
  editingProduct?: MasterBarangWithType | null
  types: MasterType[]  // This is now the actual array, not ApiResponse
  kodeOutlet: string
  isSubmitting: boolean
}

function ProductFormDialog({
  isOpen,
  onClose,
  onSubmit,
  editingProduct,
  types,
  kodeOutlet,
  isSubmitting,
}: ProductFormDialogProps) {
  const [formData, setFormData] = useState({
    sku: '',
    id_type: null as number | null,
    name: '',
    deleted: false,
    image1_url: '',
    iamge2_url: '',
  })

  // Reset form when editingProduct changes or dialog opens
  useEffect(() => {
    if (isOpen) {
      setFormData({
        sku: editingProduct?.sku || '',
        id_type: editingProduct?.id_type || null,
        name: editingProduct?.name || '',
        deleted: editingProduct?.deleted || false,
        image1_url: editingProduct?.image1_url || '',
        iamge2_url: editingProduct?.iamge2_url || '',
      })
    }
  }, [isOpen, editingProduct])

  if (!isOpen) return null

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    await onSubmit(formData)
  }

  const handleChange = (field: string, value: string | number | boolean | null) => {
    setFormData((prev) => ({ ...prev, [field]: value }))
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="bg-background w-full max-w-lg rounded-lg shadow-lg p-6">
        <h2 className="text-xl font-semibold mb-4">
          {editingProduct ? 'Edit Product' : 'New Product'}
        </h2>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* SKU */}
          <div>
            <Label htmlFor="sku">SKU / Product Code</Label>
            <Input
              id="sku"
              value={formData.sku || ''}
              onChange={(e) => handleChange('sku', e.target.value)}
              placeholder={editingProduct ? 'Loaded from database' : 'Auto-generated by database'}
              readOnly={!!editingProduct}
              disabled={!editingProduct}
              className={editingProduct ? 'bg-muted' : 'bg-muted'}
            />
            <p className="text-muted-foreground text-xs mt-1">
              {!editingProduct
                ? 'SKU will be auto-generated by database (format: ZP25XII0001)'
                : 'SKU from database (read-only)'}
            </p>
          </div>

          {/* Product Type */}
          <div>
            <Label htmlFor="id_type">Product Type</Label>
            <select
              id="id_type"
              value={formData.id_type || ''}
              onChange={(e) => handleChange('id_type', e.target.value ? Number(e.target.value) : null)}
              className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              required
            >
              <option value="">Select type...</option>
              {types.map((type) => (
                <option key={type.id} value={type.id}>
                  {type.nama_type}
                </option>
              ))}
            </select>
          </div>

          {/* Product Name */}
          <div>
            <Label htmlFor="name">Product Name</Label>
            <Input
              id="name"
              value={formData.name || ''}
              onChange={(e) => handleChange('name', e.target.value)}
              placeholder="Enter product name"
              required
            />
          </div>

          {/* Image 1 URL */}
          <div>
            <Label htmlFor="image1_url">Image 1 URL</Label>
            <Input
              id="image1_url"
              value={formData.image1_url || ''}
              onChange={(e) => handleChange('image1_url', e.target.value)}
              placeholder="https://..."
            />
          </div>

          {/* Image 2 URL */}
          <div>
            <Label htmlFor="iamge2_url">Image 2 URL</Label>
            <Input
              id="iamge2_url"
              value={formData.iamge2_url || ''}
              onChange={(e) => handleChange('iamge2_url', e.target.value)}
              placeholder="https://..."
            />
          </div>

          {/* Outlet Info (read-only) */}
          <div>
            <Label>Outlet Code</Label>
            <Input value={kodeOutlet} disabled className="bg-muted" />
            <p className="text-muted-foreground text-xs mt-1">
              Auto-filled from your profile
            </p>
          </div>

          {/* Actions */}
          <div className="flex justify-end gap-3 pt-4">
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit" disabled={isSubmitting}>
              {isSubmitting ? 'Saving...' : editingProduct ? 'Update' : 'Create'}
            </Button>
          </div>
        </form>
      </div>
    </div>
  )
}

// ============================================
// MAIN PRODUCT PAGE COMPONENT
// ============================================

export function ProductPage() {
  const [page, setPage] = useState(0)
  const [searchQuery, setSearchQuery] = useState('')
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [editingProduct, setEditingProduct] = useState<MasterBarangWithType | null>(null)

  const { user } = useAuthUser()
  const { canEdit } = useCanEditProducts()
  const { canSeeAll } = useCanSeeAllOutlets()

  // Queries
  const { data, isLoading, error, refetch } = useProductsPaginated(page, 100)
  const { data: typesResponse, isLoading: typesLoading, error: typesError } = useAllTypes()
  const types = typesResponse?.data || []

  // Show error if types query failed (e.g., RLS policies not set up)
  if (typesError && !typesLoading) {
    console.error('Failed to load product types:', typesError)
  }

  // Mutations
  const createMutation = useCreateProduct()
  const updateMutation = useUpdateProduct()
  const deleteMutation = useSoftDeleteProduct()

  // Filter data based on search
  const filteredData = data?.data?.filter((product) => {
    if (!searchQuery) return true
    const query = searchQuery.toLowerCase()
    return (
      product.name?.toLowerCase().includes(query) ||
      product.sku?.toLowerCase().includes(query) ||
      product.master_type?.nama_type?.toLowerCase().includes(query)
    )
  }) || []

  const pageSize = 100
  const totalPages = Math.ceil((data?.count || 0) / pageSize)

  const handleCreate = () => {
    if (!user?.kode_outlet) {
      toast.error('Your profile does not have an outlet assigned. Please contact administrator.')
      return
    }
    setEditingProduct(null)
    setIsDialogOpen(true)
  }

  const handleEdit = (product: MasterBarangWithType) => {
    setEditingProduct(product)
    setIsDialogOpen(true)
  }

  const handleDelete = async (product: MasterBarangWithType) => {
    if (!confirm(`Are you sure you want to delete "${product.name || 'Unnamed product'}"?`)) {
      return
    }

    const result = await deleteMutation.mutateAsync({
      kodeOutlet: product.kode_outlet,
      id: product.id,
    })

    if (result.isSuccess) {
      toast.success('Product deleted successfully')
      refetch()
    } else {
      toast.error(result.error || 'Failed to delete product')
    }
  }

  const handleSubmit = async (formData: Omit<MasterBarangWithType, 'id' | 'created_at' | 'kode_outlet' | 'master_type' | 'master_outlet'>) => {
    // When creating new product, exclude 'sku' so database trigger generates it
    // When editing, include all fields including 'sku'
    const submitData = editingProduct
      ? formData
      : (({ sku, ...rest }) => rest)(formData) as typeof formData

    const result = editingProduct
      ? await updateMutation.mutateAsync({
        kodeOutlet: editingProduct.kode_outlet,
        id: editingProduct.id,
        data: submitData,
      })
      : await createMutation.mutateAsync(submitData)

    if (result.isSuccess) {
      toast.success(editingProduct ? 'Product updated successfully' : 'Product created successfully')
      setIsDialogOpen(false)
      refetch()
    } else {
      toast.error(result.error || 'Failed to save product')
    }
  }

  const handlePrevPage = () => {
    if (page > 0) setPage(page - 1)
  }

  const handleNextPage = () => {
    if (page < totalPages - 1) setPage(page + 1)
  }

  if (isLoading) {
    return (
      <DashboardLayout>
        <div className="flex items-center justify-center h-64">
          <p className="text-muted-foreground">Loading products...</p>
        </div>
      </DashboardLayout>
    )
  }

  if (error) {
    return (
      <DashboardLayout>
        <div className="flex flex-col items-center justify-center h-64 gap-4">
          <p className="text-destructive">Failed to load products</p>
          <Button onClick={() => refetch()}>Retry</Button>
        </div>
      </DashboardLayout>
    )
  }

  return (
    <ProtectedRoute allowedRoles={[1, 5, 6, 8]}>
      <DashboardLayout>
        <div className="space-y-6">
          {/* Header */}
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold">Products</h1>
              <p className="text-muted-foreground mt-1">
                Manage your product inventory
                {!canSeeAll && user?.kode_outlet && (
                  <span> (Outlet: {user.kode_outlet})</span>
                )}
                {user?.user_role === 8 && (
                  <span className="text-amber-600 font-medium"> - Read-only access</span>
                )}
              </p>
            </div>
            {canEdit && (
              <Button onClick={handleCreate}>
                <Plus className="mr-2 h-4 w-4" />
                New Product
              </Button>
            )}
          </div>

          {/* Stats Cards */}
          <div className="grid gap-4 md:grid-cols-4">
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium">Total Products</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{data?.count || 0}</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium">Page</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{page + 1} / {totalPages || 1}</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium">Showing</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{filteredData.length}</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium">Role Access</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm font-medium">
                  {canSeeAll ? 'All Outlets' : 'Own Outlet Only'}
                </div>
                {!canEdit && (
                  <p className="text-amber-600 text-xs mt-1">Read-only</p>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Search */}
          <Card>
            <CardContent className="pt-6">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input
                  placeholder="Search by name, SKU, or type..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>
            </CardContent>
          </Card>

          {/* Data Table */}
          <Card className="border-pastel-blue/20 shadow-sm">
            <CardContent className="p-0">
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-pastel-blue/30 text-blue-900">
                    <tr>
                      <th className="px-4 py-3 text-left text-sm font-medium">SKU</th>
                      <th className="px-4 py-3 text-left text-sm font-medium">Product Name</th>
                      <th className="px-4 py-3 text-left text-sm font-medium">Type</th>
                      <th className="px-4 py-3 text-left text-sm font-medium">Outlet</th>
                      <th className="px-4 py-3 text-left text-sm font-medium">Status</th>
                      {canEdit && (
                        <th className="px-4 py-3 text-right text-sm font-medium">Actions</th>
                      )}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-pastel-blue/10">
                    {filteredData.length === 0 ? (
                      <tr>
                        <td colSpan={canEdit ? 6 : 5} className="px-4 py-8 text-center text-muted-foreground">
                          No products found
                        </td>
                      </tr>
                    ) : (
                      filteredData.map((product) => (
                        <tr key={`${product.kode_outlet}-${product.id}`} className="hover:bg-pastel-blue/10 transition-colors">
                          <td className="px-4 py-3 text-sm">{product.sku || '-'}</td>
                          <td className="px-4 py-3 text-sm font-medium">{product.name || '-'}</td>
                          <td className="px-4 py-3 text-sm">
                            {product.master_type?.nama_type || '-'}
                          </td>
                          <td className="px-4 py-3 text-sm">
                            {product.master_outlet?.name_outlet || product.kode_outlet}
                          </td>
                          <td className="px-4 py-3 text-sm">
                            {product.deleted ? (
                              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800">
                                Deleted
                              </span>
                            ) : (
                              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-pastel-green text-green-800">
                                Active
                              </span>
                            )}
                          </td>
                          {canEdit && (
                            <td className="px-4 py-3 text-sm">
                              <div className="flex justify-end gap-2">
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-8 w-8 hover:bg-pastel-blue/50 hover:text-blue-700"
                                  onClick={() => handleEdit(product)}
                                >
                                  <Pencil className="h-4 w-4" />
                                </Button>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-8 w-8 hover:bg-red-100 hover:text-red-700"
                                  onClick={() => handleDelete(product)}
                                >
                                  <Trash2 className="h-4 w-4" />
                                </Button>
                              </div>
                            </td>
                          )}
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>

          {/* Pagination */}
          <div className="flex items-center justify-between">
            <p className="text-sm text-muted-foreground">
              Showing {filteredData.length} of {data?.count || 0} products
            </p>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="icon"
                onClick={handlePrevPage}
                disabled={page === 0}
              >
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <span className="text-sm">
                Page {page + 1} of {totalPages || 1}
              </span>
              <Button
                variant="outline"
                size="icon"
                onClick={handleNextPage}
                disabled={page >= totalPages - 1}
              >
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>

        {/* Form Dialog */}
        <ProductFormDialog
          isOpen={isDialogOpen}
          onClose={() => setIsDialogOpen(false)}
          onSubmit={handleSubmit}
          editingProduct={editingProduct}
          types={types}
          kodeOutlet={user?.kode_outlet || ''}
          isSubmitting={createMutation.isPending || updateMutation.isPending}
        />
      </DashboardLayout>
    </ProtectedRoute>
  )
}
